# Generated by Django 4.2 on 2024-08-30 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_quentitiy_product_quantitiy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantitiy',
            new_name='quantity',
        ),
    ]
